### ISSUE TITLE
generator code

### ISSUE THREAD

**Issue by 1251480932** [yafuly/SyntacticGen#2]
Can you disclose how to grammar control the generated using beam search code?
How can we implement score control on beam search to generate desired sentences? What is the input in the grammar control code?  

Based on your previous reply, I successfully applied it to my dataset. Thank you very much for your work.

**Comment by yafuly** [comment]
Merging this issue into [#3](https://github.com/yafuly/SyntacticGen/issues/3) for continued discussion.
